name: Convert Clash Rules to Hosts

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write  # ⬅️ 这行是关键！

jobs:
  update-hosts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Download adrules
        run: curl -sSL -o adrules.txt https://raw.githubusercontent.com/Cats-Team/AdRules/main/adrules_domainset.txt

      - name: Convert to hosts
        run: python3 scripts/convert_to_hosts.py adrules.txt hosts.txt

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "daily: update hosts.txt"
          file_pattern: hosts.txt